# Generated by Django 4.1.3 on 2022-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("github", models.CharField(max_length=100)),
                ("blog", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=10000)),
            ],
        ),
    ]
