# Generated by Django 4.1.3 on 2022-12-03 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("article_app", "0002_introduction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="date", new_name="create_date",
        ),
        migrations.AddField(
            model_name="article", name="content", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="genre",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "SwHw"),
                    (2, "AdvancedCS"),
                    (3, "Science"),
                    (4, "Economics"),
                    (5, "Philosophy"),
                    (6, "Life"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="update_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
